client/config/routes.rb
Rails.application.routes.draw do

  resources :projects

end

client/app/models/project.rb
class Project < ActiveRecord::Base
end

client/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

client/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
    @projects = Project.all
	end
  
  def show
    @project = Project.find(params[:id])
  end
  
  def new 
    @project = Project.new
  end
  
  def create
    @project= Project.new(params[:project].permit(:title,:abstract,:client))
    if @project.save
      redirect_to projects_path, :notice => "Your project was succesfully saved"
    else
      render "new"
    end
    
  end
  
  def edit 
    @project = Project.find(params[:id])  
    
  end
  
  def update
    @project = Project.find(params[:id])
    
    if @project.update_attributes(params[:project].permit(:title,:client,:abstract))
      redirect_to projects_path, :notice => "Your project was succesfully updated"
    else
      render "edit"

  end
  
end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path, :notice => "Your project has been deleted"
  end
  
end

client/app/helpers/application_helper.rb
module ApplicationHelper
end

client/app/helpers/projects_helper.rb
module ProjectsHelper
end

client/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Client</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

client/app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= form_for @project do |form| %>
<p>
	<%= form.label :title %>< br />
	<%= form.text_field :title %>
</p>
<p>
	<%= form.label :client %>< br />
	<%= form.text_area :client %>
</p>
<p>
	<%= form.label :abstract %>< br />
	<%= form.text_area :abstract %>
</p>
<p> 
	<%= form.submit "Update Project"%>
</p>
<% end %>

client/app/views/projects/index.html.erb
<h1>Projects</h1>
<p><%= link_to "Propose a new projectt", new_project_path %>
<% @projects.each do |project| %>
	<h2><%= project.title %></h2>
	<h3><%= project.client %></h3>
	<p><%= project.abstract %></p>
	<p><%= link_to "Edit", edit_project_path(project) %></p>
	<p><%= link_to "Delete", project, :confirm => "Are you sure?", :method => :delete %></p>
	<hr />
<% end %>

client/app/views/projects/new.html.erb
<h1>Propose a New Project</h1>

<%= form_for @project do |form| %>
	<p>
		<%= form.label :title %>
		<%= form.text_field :title %>
	</p>
	<p>
		<%= form.label :client %>
		<%= form.text_area :client %>
	</p>
	<p>
		<%= form.label :abstract %>
		<%= form.text_area :abstract %>
	</p>
	<p>
		<%= form.submit "Submit your Proposalt" %>
	</p>

<% end %>

client/app/views/projects/show.html.erb
<h1><%= @project.title %></h1>
<h2><%= @project.client %></h2>
<p><%= @project.abstract %></p>
<small><%= @project.created_at %></small>